Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fitness_Center_Management.Models;

public partial class Trainer
{
    public decimal Trainersid { get; set; }

    public string Firstname { get; set; } = null!;

    public string Lastname { get; set; } = null!;

    public string? Expertise { get; set; }

    public string? Picture { get; set; }

    [NotMapped]
    public virtual IFormFile? PictureUrl { get; set; }

    public string? Socialfacebook { get; set; }

    public string? Socialtwitter { get; set; }

    public string? Sociallinkedin { get; set; }

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<Trainerclass> Trainerclasses { get; set; } = new List<Trainerclass>();
}

Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fitness_Center_Management.Models;
using Microsoft.AspNetCore.Hosting;

namespace Fitness_Center_Management.Controllers
{
    public class TrainersController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TrainersController(ModelContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Trainers
        public async Task<IActionResult> Index()
        {
              return _context.Trainers != null ? 
                          View(await _context.Trainers.ToListAsync()) :
                          Problem("Entity set 'ModelContext.Trainers'  is null.");
        }

        // GET: Trainers/Search
        [HttpGet]
        public IActionResult Search()
        {
            // Return the search view
            return View();
        }

        // POST: Trainers/Search
        [HttpPost]
        public async Task<IActionResult> Search(string? searchQuery)
        {
            // Check if the search query is null or empty
            if (string.IsNullOrEmpty(searchQuery))
            {
                // If no query, return all trainers
                var allTrainers = await _context.Trainers.ToListAsync();
                return View("Index", allTrainers);  // Return to the Index view
            }

            // Otherwise, filter trainers based on search query (FirstName, LastName, or Username)
            var filteredTrainers = await _context.Trainers
                .Where(t => t.Firstname.ToLower().Contains(searchQuery.ToLower()) ||
                            t.Lastname.ToLower().Contains(searchQuery.ToLower()) ||
                            t.Username.ToLower().Contains(searchQuery.ToLower()))
                .ToListAsync();

            // Return the filtered list of trainers
            return View("Index", filteredTrainers);  // Pass the filtered trainers to the same Index view
        }


        // GET: Trainers/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null || _context.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers
                .FirstOrDefaultAsync(m => m.Trainersid == id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        // GET: Ttainers/Members
        public async Task<IActionResult> Members()
        {
            ViewData["TrainerId"] = HttpContext.Session.GetInt32("trainerId");
            return _context.Users != null ?
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'ModelContext.Users'  is null.");
        }

        // GET: Trainers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trainers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Trainersid,Firstname,Lastname,Expertise,PictureUrl,Socialfacebook,Socialtwitter,Sociallinkedin,Username,Password")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                if (trainer.PictureUrl != null)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Guid.NewGuid().ToString() + "_" + trainer.PictureUrl.FileName;
                    string path = Path.Combine(wwwRootPath + "/Images/", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await trainer.PictureUrl.CopyToAsync(fileStream);
                    }
                    trainer.Picture = fileName;
                }

                _context.Add(trainer);

                Userlogin userlogin = new Userlogin
                {
                    Roleid = 2,
                    Username = trainer.Username,
                    Password = trainer.Password
                };
                _context.Add(userlogin);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Trainers/Edit/2
        public async Task<IActionResult> Edit(decimal? id)
        {
            ViewData["TrainerId"] = HttpContext.Session.GetInt32("trainerId");
            if (id == null || _context.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }
            return View(trainer);
        }

        // POST: Trainers/Edit/2
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("Trainersid,Firstname,Lastname,Expertise,PictureUrl,Socialfacebook,Socialtwitter,Sociallinkedin,Username,Password")] Trainer trainer)
        {
            if (id != trainer.Trainersid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Fetch the existing admin from the database
                    var existingTrainer = await _context.Trainers.AsNoTracking().FirstOrDefaultAsync(t => t.Trainersid == id);

                    if (existingTrainer == null)
                    {
                        return NotFound();
                    }

                    if (trainer.PictureUrl != null)
                    {
                        string wwwRootPath = _webHostEnvironment.WebRootPath;
                        string fileName = Guid.NewGuid().ToString() + "_" + trainer.PictureUrl.FileName;
                        string path = Path.Combine(wwwRootPath + "/Images/", fileName);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await trainer.PictureUrl.CopyToAsync(fileStream);
                        }

                        trainer.Picture = fileName;

                    }

                    // Find and update the corresponding Userlogin record if it exists
                    var userlogin = await _context.Userlogins.FirstOrDefaultAsync(u => u.Username == existingTrainer.Username);
                    if (userlogin != null)
                    {
                        // Update the Admin entity
                        _context.Update(trainer);

                        userlogin.Username = trainer.Username;
                        userlogin.Password = trainer.Password;

                        _context.Update(userlogin);
                    }

                    // Save changes to the database
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainerExists(trainer.Trainersid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new {id});
            }

            return View(trainer);
        }


        // GET: Trainers/Delete/2
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null || _context.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers
                .FirstOrDefaultAsync(m => m.Trainersid == id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        // POST: Trainers/Delete/2
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            if (_context.Trainers == null)
            {
                return Problem("Entity set 'ModelContext.Trainers'  is null.");
            }

            var trainer = await _context.Trainers.FindAsync(id);
            
            if (trainer != null)
            {
                var userlogin = await _context.Userlogins.FirstOrDefaultAsync(u => u.Username == trainer.Username);
                if (userlogin != null)
                {
                    _context.Userlogins.Remove(userlogin);
                }

                _context.Trainers.Remove(trainer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainerExists(decimal id)
        {
          return (_context.Trainers?.Any(e => e.Trainersid == id)).GetValueOrDefault();
        }
    }
}

Views/Trainers/Create.cshtml
@model Fitness_Center_Management.Models.Trainer

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Trainer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expertise" class="control-label"></label>
                <input asp-for="Expertise" class="form-control" />
                <span asp-validation-for="Expertise" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Socialfacebook" class="control-label"></label>
                <input asp-for="Socialfacebook" class="form-control" />
                <span asp-validation-for="Socialfacebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Socialtwitter" class="control-label"></label>
                <input asp-for="Socialtwitter" class="form-control" />
                <span asp-validation-for="Socialtwitter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sociallinkedin" class="control-label"></label>
                <input asp-for="Sociallinkedin" class="form-control" />
                <span asp-validation-for="Sociallinkedin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Views/Trainers/Delete.cshtml
@model Fitness_Center_Management.Models.Trainer

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Expertise)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Expertise)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Socialfacebook)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Socialfacebook)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Socialtwitter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Socialtwitter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sociallinkedin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sociallinkedin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Trainersid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Trainers/Details.cshtml
@model Fitness_Center_Management.Models.Trainer

@{
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}

<div class="container">
    <div class="admin-profile">
        <div class="admin-header">
            <img src="@Url.Content("~/Images/" + @Model.Picture)" alt="Admin Profile Picture" />
            <h1>@Html.DisplayFor(Model => Model.Firstname) @Html.DisplayFor(Model => Model.Lastname)</h1>
        </div>
        <div class="admin-details">
            <h5>Username</h5>
            <p>@Html.DisplayFor(Model => Model.Username)</p>

            <h5>Password</h5>
            <p>@Html.DisplayFor(Model => Model.Password)</p>
        </div>
        <div class="admin-actions">
            <a class="btn btn-primary btn-lg btn-edit" asp-controller="Trainers" asp-action="Edit" 
                asp-route-id="@Model.Trainersid" >
                Edit Profile
            </a>
        </div>
    </div>
</div>

<style>
    body {
        background-color: #f8f9fa;
    }

    .admin-profile {
        margin: 0 auto;
        padding: 20px 30px;
        background: #fff;
        border-radius: 15px;
        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
        max-width: 900px;
    }

    .admin-header {
        text-align: center;
        margin-bottom: 30px;
    }

        .admin-header img {
            border-radius: 50%;
            width: 150px;
            height: 150px;
            object-fit: cover;
            margin-bottom: 20px;
            border: 2px solid #4B49AC;
        }

        .admin-header h1 {
            font-size: 2.5rem;
            font-weight: bold;
            color: #343a40;
        }

        .admin-header p {
            font-size: 1.2rem;
            color: #6c757d;
        }

    .admin-details {
        margin: 20px 0;
    }

        .admin-details h5 {
            font-weight: bold;
            color: #495057;
            margin-bottom: 10px;
        }

        .admin-details p {
            font-size: 1.1rem;
            color: #6c757d;
            margin-bottom: 20px;
            border-bottom: 1px solid #dee2e6;
            padding-bottom: 10px;
        }

    .admin-actions {
        text-align: center;
        margin-top: 30px;
    }

        .admin-actions .btn {
            margin: 0 10px;
        }

</style>

Views/Trainers/Edit.cshtml
@model Fitness_Center_Management.Models.Trainer

@{
   Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Trainer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Trainersid" />
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expertise" class="control-label"></label>
                <input asp-for="Expertise" class="form-control" />
                <span asp-validation-for="Expertise" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Socialfacebook" class="control-label"></label>
                <input asp-for="Socialfacebook" class="form-control" />
                <span asp-validation-for="Socialfacebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Socialtwitter" class="control-label"></label>
                <input asp-for="Socialtwitter" class="form-control" />
                <span asp-validation-for="Socialtwitter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sociallinkedin" class="control-label"></label>
                <input asp-for="Sociallinkedin" class="form-control" />
                <span asp-validation-for="Sociallinkedin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@ViewData["trainerId"]">Back</a>
</div>

</body>
</html>

Views/Trainers/Index.cshtml
@model IEnumerable<Fitness_Center_Management.Models.Trainer>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Trainer List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" />
    <style>
        .trainer-card {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin: 15px;
            transition: all 0.3s ease-in-out;
        }

            .trainer-card:hover {
                transform: translateY(-10px);
                box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
            }

            .trainer-card img {
                border-radius: 10px;
                object-fit: cover;
                width: 100%;
                height: 200px;
            }

            .trainer-card .card-body {
                padding: 20px;
            }

            .trainer-card h5 {
                color: #343a40;
            }

            .trainer-card p {
                font-size: 1rem;
                color: #6c757d;
            }

        .trainer-actions {
            text-align: center;
            margin-top: 15px;
        }

            .trainer-actions .btn {
                margin: 5px;
            }

        a {
            text-decoration: none;
        }

        .search-container input {
            margin-right: 10px;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="text-center">
            <a  asp-action="Index" style="text-decoration: none;">
                <h1 style="background-color: none;">Trainers</h1>
            </a>
        </div>

        <div class="d-flex justify-content-between mb-4">
            <!-- Create New Button -->
            <a class="btn btn-primary" asp-action="Create">Create New Trainer</a>

            <!-- Search Button and Input -->
            <div class="search-container">
                <form method="post" action="@Url.Action("Search", "Trainers")">
                    <input type="text" name="searchQuery" class="form-control" placeholder="Search Trainers..." style="width: 300px; display: inline-block;" />
                    <button type="submit" class="btn btn-secondary">Search</button>
                </form>
            </div>

        </div>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var item in Model)
            {
                <div class="col">
                    <div class="card trainer-card">
                        <img src="@Url.Content("~/Images/" + item.Picture)" alt="Trainer Image" />
                        <div class="card-body">
                            <h5 class="card-title">@item.Firstname @item.Lastname</h5>
                            <p class="card-text">Expertise: @item.Expertise</p>
                            <p class="card-text">Username: @item.Username</p>
                            <p class="card-text">Password: @item.Password</p>

                            <p class="card-text">
                                Social Links:
                                <a href="@item.Socialfacebook" target="_blank">Facebook</a>,
                                <a href="@item.Socialtwitter" target="_blank">Twitter</a>,
                                <a href="@item.Sociallinkedin" target="_blank">LinkedIn</a>
                            </p>
                        </div>
                        <div class="trainer-actions">
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Trainersid">Delete</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Views/Trainers/Members.cshtml
@model IEnumerable<Fitness_Center_Management.Models.User>

@{
    ViewData["Title"] = "Members";
    Layout = "~/Views/Shared/_TrainerLayout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Users</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container">
        <div class="text-center pb-5">
            <h1>Members</h1>
        </div>

        <table class="table table-striped table-bordered align-middle py-5">
            <thead class="table-dark">
                <tr>
                    <th>Picture</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Registration Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">
                            @if (!string.IsNullOrEmpty(item.Picture))
                            {
                                <img src="~/Images/@item.Picture" alt="User Picture" class="rounded-circle" style="width: 50px; height: 50px;" />
                            }
                            else
                            {
                                <img src="~/Images/default-user.png" alt="Default Picture" class="rounded-circle" style="width: 50px; height: 50px;" />
                            }
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Firstname)</td>
                        <td>@Html.DisplayFor(modelItem => item.Lastname)</td>
                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                        <td>@Html.DisplayFor(modelItem => item.Phonenumber)</td>
                        <td>@string.Format("{0:0.#}", item.Age)</td>
                        <td>@Html.DisplayFor(modelItem => item.Gender)</td>
                        <td>@Html.DisplayFor(modelItem => item.Registrationdate)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.js"></script>
</body>
</html>